### ISSUE TITLE
Actor won't turn on with a delay of more than a few seconds

### ISSUE THREAD

**Issue by stpoli2468** [pascal1404/cbpi4_compressorActor#1]
Hi, the Actor won't turn on with a delay of more than a few seconds, if i spam the button after a few click it start.

it would be cool te put the timer in a "sensor" to add it in the dashboard, if it is not running we would know at first glance that the timer is not "finished".

**Comment by pascal1404** [comment]
Did you use my repo off cbpi4 and cbpi4-ui? Because in my dashboard it works perfect, and the button shows the remaing time and a progressbar. This works for me also with times like 90 or 600 seconds. 
https://www.dropbox.com/s/49euhtxj4zecp6c/vid_20220424_213056.mp4?dl=0
